controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

guide_michelin:
  resource: routes/guide/routes.yaml
  prefix: /guideMichelin

chef:
  resource: routes/chef/routes.yaml
  prefix: /chef

plat:
  resource: routes/plat/routes.yaml
  prefix: /plat
