guide_michelin_accueil:
  path: /accueil/{nom}
  controller: App\Controller\GuideMichelinController::accueil
  defaults:
    nom: ""

guide_michelin_menu:
  path: /menu
  controller: App\Controller\GuideMichelinController::menu

guide_michelin_voir:
  path: /resto/voir/{id}
  controller: App\Controller\GuideMichelinController::voir
  requirements:
    id: \d+

guide_michelin_ajouter:
  path: /resto/ajouter/{nom}-{chef}-{etoile}
  controller: App\Controller\GuideMichelinController::add
  requirements:
    nom: \w+
    chef: \w+
    etoile: 0|1|2|3|4|5

guide_michelin_ajouter2:
  path: /resto/ajouter2
  controller: App\Controller\GuideMichelinController::add2

guide_michelin_list:
  path: resto/list
  controller: App\Controller\GuideMichelinController::list

guide_michelin_modifier:
  path: resto/modifier/{id}
  controller: App\Controller\GuideMichelinController::modifier

guide_michelin_modifier_suite:
  path: resto/modifierSuite/{id}
  controller: App\Controller\GuideMichelinController::modifierSuite
  methods: POST

guide_michelin_delete:
  path: resto/supprimer/{id}
  controller: App\Controller\GuideMichelinController::delete
  requirements:
    id: \d+

guide_michelin_list_cond:
  path: resto/list/{etoile}
  controller: App\Controller\GuideMichelinController::list2
  requirements:
    nbEtoile: 0|1|2|3|4|5

guide_michelin_list_cond_inf:
  path: resto/list_inf/{etoile}
  controller: App\Controller\GuideMichelinController::list3
  requirements:
    nbEtoile: 0|1|2|3|4|5

guide_michelin_list_cond_sup:
  path: resto/list_sup/{etoile}
  controller: App\Controller\GuideMichelinController::list4
  requirements:
    nbEtoile: 0|1|2|3|4|5

guide_michelin_ajouter_etoile:
  path: resto/ajouter_etoile
  controller: App\Controller\GuideMichelinController::ajouterEtoile

guide_michelin_find_by_chef:
  path: resto/find_by_chef/{chef}
  controller: App\Controller\GuideMichelinController::findByChef

guide_michelin_id_list:
  path: resto/edit/
  controller: App\Controller\GuideMichelinController::listId

guide_michelin_edit_resto:
  path: resto/edit/{id}-{nom}-{nom_chef}-{nbEtoile}
  controller: App\Controller\GuideMichelinController::modifier2
