guide_michelin_accueil:
  path: /accueil/{nom}
  controller: App\Controller\GuideMichelinController::accueil
  defaults:
    nom: ""

guide_michelin_menu:
  path: /menu
  controller: App\Controller\GuideMichelinController::menu

guide_michelin_voir:
  path: /resto/voir/{id}
  controller: App\Controller\GuideMichelinController::voir
  requirements:
    id: \d+

guide_michelin_ajouter:
  path: /resto/ajouter/{nom}-{chef}-{etoile}
  controller: App\Controller\GuideMichelinController::add
  requirements:
    nom: \w+
    chef: \w+
    etoile: 0|1|2|3|4|5

guide_michelin_ajouter2:
  path: /resto/ajouter2
  controller: App\Controller\GuideMichelinController::add2

guide_michelin_list:
  path: resto/list
  controller: App\Controller\GuideMichelinController::list

guide_michelin_modifier:
  path: resto/modifier/{id}
  controller: App\Controller\GuideMichelinController::modifier

guide_michelin_modifier_suite:
  path: resto/modifierSuite/{id}
  controller: App\Controller\GuideMichelinController::modifierSuite
  methods: POST

guide_michelin_delete:
  path: resto/supprimer/{id}
  controller: App\Controller\GuideMichelinController::delete
  requirements:
    id: \d+
